version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  springboot-mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "springboot-mongodb"
    ports:
      - 8090:8090
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - server.port=8090
